[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "document-service"
version = "1.0.0"
description = "Document processing and storage service for the Enrollment System, providing secure document management, verification, and storage capabilities"
authors = ["Enrollment System Team <team@enrollmentsystem.com>"]
readme = "README.md"
license = "Proprietary"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.0"
uvicorn = "^0.23.0"
python-multipart = "^0.0.6"
mongoengine = "^0.27.0"
boto3 = "^1.28.0"
pydantic = "^2.0.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
grpcio = "^1.56.0"
grpcio-tools = "^1.56.0"
prometheus-client = "^0.17.0"
structlog = "^23.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.1.0"
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.4.0"
flake8 = "^6.0.0"
mongomock = "^4.1.2"
moto = "^4.1.11"
httpx = "^0.24.0"

[tool.poetry.scripts]
start = "src.app:main"

[tool.black]
line-length = 100
target-version = ["py311"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
plugins = ["pydantic.mypy"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=src --cov-report=term-missing"
asyncio_mode = "auto"

[tool.coverage.run]
source = ["src"]
omit = ["tests/*", "**/__init__.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "pass",
    "raise ImportError",
]
fail_under = 80

[tool.poetry.urls]
repository = "https://github.com/organization/enrollment-system"
documentation = "https://docs.enrollmentsystem.com"