# Prometheus configuration file v2.45.0
# Configures metrics collection, alerting, and storage for the enrollment system

global:
  # Global settings for all scrape targets
  scrape_interval: 15s     # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules
  scrape_timeout: 10s     # Timeout for scrape requests
  
  # External labels to identify this Prometheus instance
  external_labels:
    environment: production
    region: primary
    system: enrollment

# Scrape configurations for all services
scrape_configs:
  # API Gateway metrics
  - job_name: api-gateway
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['api-gateway:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: api-gateway
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^gateway_.*$'
        action: keep

  # Authentication Service metrics
  - job_name: auth-service
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['auth-service:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: auth-service
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^auth_.*$'
        action: keep

  # Application Service metrics (Spring Boot Actuator)
  - job_name: application-service
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ['application-service:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: application-service
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^application_.*$'
        action: keep

  # Document Service metrics
  - job_name: document-service
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['document-service:5000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: document-service
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^document_.*$'
        action: keep

  # Notification Service metrics
  - job_name: notification-service
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['notification-service:3001']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: notification-service
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^notification_.*$'
        action: keep

  # Workflow Service metrics (Spring Boot Actuator)
  - job_name: workflow-service
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ['workflow-service:8082']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: workflow-service
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^workflow_.*$'
        action: keep

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      timeout: 5s
      api_version: v2

# Rule files for alerts and recording rules
rule_files:
  - "rules/alert.rules.yml"
  - "rules/recording.rules.yml"

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention_time: 15d      # Data retention period
    retention_size: 50GB     # Maximum storage size
    wal_compression: true    # Enable WAL compression
    min_block_duration: 2h   # Minimum block time
    max_block_duration: 24h  # Maximum block time

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "http://remote-storage:9201/write"
#     remote_timeout: 30s
#     queue_config:
#       capacity: 500
#       max_shards: 1000
#       max_samples_per_send: 100

# Remote read configuration for historical data (optional)
# remote_read:
#   - url: "http://remote-storage:9201/read"
#     read_recent: true